name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  drawing_animation: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/0.svg
    - assets/1.svg
    - assets/2.svg
    - assets/3.svg
    - assets/4.svg
    - assets/5.svg
    - assets/6.svg
    - assets/7.svg
    - assets/8.svg
    - assets/9.svg
    - assets/s.svg
    - assets/clear.svg
